### ISSUE TITLE
[WIKI_001] 위키 등록

### ISSUE THREAD

**Issue by dlrkdms125** [beyond-sw-camp/be06-fin-SENAGAE-Enadu#23]
1. 회원만 등록 가능
2. 3가지 항목 입력 필수
3. 썸네일 등록 안할 시 썸네일 시퀀스는 0, 썸네일 아니면 1로 반환
4. 썸네일 따로 등록도 가능
5. 멀티파트 파일로 받아서 이미지는 S3에 업로드하고 DB에는 이미지 URL 저장

**Comment by jimnyy** [comment]
- 썸네일, 유저 Req에 따른 등록 구현
- 썸네일 미등록시 S3에 등록해놓은 기본이미지 URL 받아와서 랜덤 업로드 구현
- 위키 등록 예외처리 구현
- 최초 위키 등록시 최신위키 처리
- 최조 위키 등록시 버전 1 고정

**Comment by jimnyy** [comment]
- 이미 등록된 주제의 위키일시, 예외 처리
- Req에 title, content, category 셋 중 하나라도 미등록시 예외처리
- 기본 썸네일 업로드 메서드 수정
